/*****************************************************************************\

Copyright (C) 2026 Intel Corporation

SPDX-License-Identifier: MIT

File Name:  ExtensionVersions.h

Abstract:   Modern Graphics Extensions version enum and per-platform
            supported-version table

\*****************************************************************************/
#pragma once

#include "igdext.h"

enum INTC_EXTENSION_VERSION
{
    EXTENSION_HW_FEATURE_LEVEL_1 = 1, // HW Feature Level 1 - Gen9
    EXTENSION_HW_FEATURE_LEVEL_2 = 2, // HW Feature Level 2 - Gen11
    EXTENSION_HW_FEATURE_LEVEL_3 = 3, // HW Feature Level 3 - Gen12LP
    EXTENSION_HW_FEATURE_LEVEL_4 = 4, // HW Feature Level 4 - Xe Architecture
    EXTENSION_HW_FEATURE_LEVEL_5 = 5, // HW Feature Level 5 - Xe2 Architecture

    EXTENSION_API_VERSION_0  = 0,  // API Version 0
    EXTENSION_API_VERSION_1  = 1,  // API Version 1
    EXTENSION_API_VERSION_2  = 2,  // API Version 2
    EXTENSION_API_VERSION_4  = 4,  // API Version 4
    EXTENSION_API_VERSION_5  = 5,  // API Version 5
    EXTENSION_API_VERSION_6  = 6,  // API Version 6
    EXTENSION_API_VERSION_7  = 7,  // API Version 7
    EXTENSION_API_VERSION_8  = 8,  // API Version 8
    EXTENSION_API_VERSION_9  = 9,  // API Version 9
    EXTENSION_API_VERSION_10 = 10, // API Version 10
    EXTENSION_API_VERSION_11 = 11, // API Version 11
    EXTENSION_API_VERSION_12 = 12, // API Version 12
    EXTENSION_API_VERSION_13 = 13, // API Version 13
    EXTENSION_API_VERSION_14 = 14, // API Version 14
    EXTENSION_API_VERSION_15 = 15, // API Version 15
    EXTENSION_API_VERSION_16 = 16, // API Version 16
    EXTENSION_API_VERSION_18 = 18, // API Version 18
    EXTENSION_API_VERSION_19 = 19, // API Version 19
    EXTENSION_API_VERSION_20 = 20, // API Version 20

    EXTENSION_REVISION_0 = 0, // Revision Version 0
    EXTENSION_REVISION_1 = 1, // Revision Version 1
};

// Kept as the real historical compat list: apps may probe for any of these older versions
// via _INTC_D3D11_GetSupportedVersions/D3D11GetSupportedVersions2, not just the current max.
const INTCExtensionVersion SupportedExtVersions[] = {
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_0, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_1, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_2, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_4, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_9, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_1, EXTENSION_API_VERSION_19, EXTENSION_REVISION_0},

    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_0, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_1, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_2, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_4, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_9, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_2, EXTENSION_API_VERSION_19, EXTENSION_REVISION_0},

    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_0, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_1, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_2, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_4, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_4, EXTENSION_REVISION_1},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_9, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_10, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_12, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_14, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_3, EXTENSION_API_VERSION_19, EXTENSION_REVISION_0},

    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_0, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_1, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_2, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_4, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_5, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_6, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_7, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_8, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_9, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_10, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_11, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_12, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_13, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_14, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_15, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_16, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_19, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_4, EXTENSION_API_VERSION_20, EXTENSION_REVISION_0},

    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_6, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_7, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_8, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_9, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_10, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_11, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_12, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_13, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_14, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_15, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_16, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_18, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_19, EXTENSION_REVISION_0},
    {EXTENSION_HW_FEATURE_LEVEL_5, EXTENSION_API_VERSION_20, EXTENSION_REVISION_0},
};
