#!/usr/bin/env python3
"""gen_dyn_dummies.py <out.inc> [fxc path]
Generates the shim's placeholder compute shaders for run-time compiled kernels (shim/src/dll/dyn_dummies.inc).
Placeholder id N is a trivial DXBC compute shader that stores the magic value 0x584D5843 (the patched ANV only replaces
shaders that store it) and whose numthreads encode N on the planes z = 7, 11, 13 (primes no game is known to use): inside
a plane every (x, y) with x * y * z <= 1024, ordered by y then x. This order must match anv_cm_dyn_id() in the ANV patch.
Needs fxc.exe (Windows SDK)."""
import os, subprocess, sys, tempfile, glob

MAGIC = 0x584D5843
PLANES = (7, 11, 13)


def ids():
    for z in PLANES:
        lim = 1024 // z
        for y in range(1, lim + 1):
            for x in range(1, lim // y + 1):
                yield x, y, z


def main():
    out = sys.argv[1]
    fxc = sys.argv[2] if len(sys.argv) > 2 else os.environ.get("FXC") or \
        (sorted(glob.glob("C:/Program Files (x86)/Windows Kits/10/bin/*/x64/fxc.exe")) or ["fxc"])[-1]
    tmp = tempfile.mkdtemp(prefix="dyndummies")
    arrays, entries = [], []
    for kid, (x, y, z) in enumerate(ids()):
        hl = os.path.join(tmp, "d%d.hlsl" % kid)
        with open(hl, "w") as f:
            f.write("RWByteAddressBuffer u0 : register(u0);\n[numthreads(%d,%d,%d)] void main() { u0.Store(0, 0x%08X); }\n"
                    % (x, y, z, MAGIC))
        co = os.path.join(tmp, "d%d.cso" % kid)
        r = subprocess.run([fxc, "/nologo", "/T", "cs_5_0", "/E", "main", "/Fo", co, hl], capture_output=True, text=True)
        if r.returncode:
            print(r.stdout, r.stderr)
            sys.exit(1)
        data = open(co, "rb").read()
        arrays.append("static const unsigned char kDynDummy%04d[] = {%s};\n" % (kid, ",".join("0x%02x" % b for b in data)))
        entries.append("    { kDynDummy%04d, sizeof(kDynDummy%04d) },  // %d,%d,%d\n" % (kid, kid, x, y, z))
    src = ("// generated by tools/gen_dyn_dummies.py: placeholder DXBC compute shaders for run-time compiled kernel ids 0..%d\n"
           "// (numthreads planes z = 7, 11, 13, every (x, y) with x*y*z <= 1024 ordered by y then x; each stores 0x%08X)\n"
           % (len(entries) - 1, MAGIC)
           + "".join(arrays) +
           "struct DynDummy { const unsigned char* bytes; size_t size; };\n"
           "static const DynDummy kDynDummies[] = {\n" + "".join(entries) + "};\n")
    with open(out, "w") as f:
        f.write(src)
    print("wrote", out, "entries", len(entries))


if __name__ == "__main__":
    main()
