#!/usr/bin/env python3
"""gen_dyn_dummies.py <out.inc> [fxc path]
Generates the shim's table of dummy compute shaders for kernels the shim has never seen (shim/src/dll/dyn_dummies.inc).
Dummy id N (0..287) is a trivial DXBC compute shader whose numthreads z is a prime no game uses (7, 11 or 13) so a
real shader can never be mistaken for one: plane z=7 holds ids 0..143 as (1+N%16, 1+N/16, 7), plane z=11 ids 144..223
as (1+M%16, 1+M/16, 11) with M=N-144, plane z=13 ids 224..287 with M=N-224 (x*y*z stays <= 1024). The static table
keeps its own (x, y, 5) plane. The patched ANV maps the workgroup back to the id, file dyn_<id>.cmk, and compiles the
kernel's SPIR-V (dumped by the shim next to the id) at run time if no packed kernel exists yet. Needs fxc.exe."""
import os, subprocess, sys, tempfile, glob
out = sys.argv[1]
fxc = sys.argv[2] if len(sys.argv) > 2 else os.environ.get("FXC") or (glob.glob("C:/Program Files (x86)/Windows Kits/10/bin/*/x64/fxc.exe") or ["fxc"])[-1]
PLANES = [(7, 144), (11, 80), (13, 64)]     # (z, ids in the plane); x = 1 + m % 16, y = 1 + m / 16 inside a plane
N = sum(n for _, n in PLANES)
def xyz(kid):
    for z, n in PLANES:
        if kid < n:
            return 1 + kid % 16, 1 + kid // 16, z
        kid -= n
    raise ValueError(kid)
tmp = tempfile.mkdtemp(prefix="dyndummies")
arrays, entries = [], []
for kid in range(N):
    x, y, z = xyz(kid)
    hl = os.path.join(tmp, "d%d.hlsl" % kid)
    open(hl, "w").write("RWByteAddressBuffer u0 : register(u0);\n[numthreads(%d,%d,%d)] void main() { u0.Store(0, 1); }\n" % (x, y, z))
    co = os.path.join(tmp, "d%d.cso" % kid)
    r = subprocess.run([fxc, "/nologo", "/T", "cs_5_0", "/E", "main", "/Fo", co, hl], capture_output=True, text=True)
    if r.returncode:
        print(r.stdout, r.stderr); sys.exit(1)
    data = open(co, "rb").read()
    arrays.append("static const unsigned char kDynDummy%04d[] = {%s};\n" % (kid, ",".join("0x%02x" % b for b in data)))
    entries.append("    { kDynDummy%04d, sizeof(kDynDummy%04d) },\n" % (kid, kid))
src = ("// generated by tools/gen_dyn_dummies.py: dummy DXBC compute shaders for dynamically assigned kernel ids 0..%d\n"
       "// numthreads planes z=7 (ids 0..143), z=11 (144..223), z=13 (224..287), x = 1+m%%16, y = 1+m/16 inside a plane;\n"
       "// the patched ANV maps the workgroup back to the id (dyn_<id>.cmk)\n" % (N - 1)
       + "".join(arrays) +
       "struct DynDummy { const unsigned char* bytes; size_t size; };\n"
       "static const DynDummy kDynDummies[] = {\n" + "".join(entries) + "};\n")
open(out, "w").write(src)
print("wrote", out, "entries", len(entries))
