#!/usr/bin/env python3
"""gen_all_dummies.py <map file> <out.inc> [fxc path]
Regenerates the shim's XeSS kernel table (shim/src/dll/xess_dummies.inc) from a kernel map written by s16_map.py
(lines: id dumpindex hash name lx ly lz typed). For every unique kernel it compiles a trivial DXBC compute shader whose
numthreads is (1+id%16, 1+id/16, 5): the shim returns it as the pipeline for that kernel hash, and the patched ANV maps
the workgroup size back to kernels/wg<x>_<y>_5.cmk. Needs fxc.exe (Windows SDK); run on Windows or under Wine."""
import os, subprocess, sys, tempfile
mapfile, out = sys.argv[1], sys.argv[2]
fxc = sys.argv[3] if len(sys.argv) > 3 else os.environ.get("FXC", "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/fxc.exe")
tmp = tempfile.mkdtemp(prefix="xessdummies")
arrays, entries = [], []
for line in open(mapfile):
    p = line.split()
    if len(p) < 8: continue
    kid, h = int(p[0]), int(p[2], 16)
    x, y = 1 + kid % 16, 1 + kid // 16
    hl = os.path.join(tmp, "d%d.hlsl" % kid)
    open(hl, "w").write("RWByteAddressBuffer u0 : register(u0);\n[numthreads(%d,%d,5)] void main() { u0.Store(0, 1); }\n" % (x, y))
    co = os.path.join(tmp, "d%d.cso" % kid)
    r = subprocess.run([fxc, "/nologo", "/T", "cs_5_0", "/E", "main", "/Fo", co, hl], capture_output=True, text=True)
    if r.returncode: print(r.stdout, r.stderr); sys.exit(1)
    data = open(co, "rb").read()
    arrays.append("static const unsigned char kXessDummy%04d[] = {%s};\n" % (kid, ",".join("0x%02x" % b for b in data)))
    entries.append("    { 0x%016xull, kXessDummy%04d, sizeof(kXessDummy%04d), %d },  // %s\n" % (h, kid, kid, kid, p[3]))
src = ("// generated by tools/gen_all_dummies.py from a XeSS kernel dump: one dummy DXBC compute shader per unique CM kernel\n"
       "// (FNV-1a of SPIR-V + compile options); the patched ANV maps workgroup (1+id%16, 1+id/16, 5) to kernels/wg<x>_<y>_5.cmk\n"
       + "".join(arrays) +
       "struct XessDummy { unsigned long long hash; const unsigned char* bytes; size_t size; int id; };\n"
       "static const XessDummy kXessDummies[] = {\n" + "".join(entries) + "};\n")
open(out, "w").write(src)
print("wrote", out, "entries", len(entries))
